[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[programs.localnet]
vault_receipt_migration = "3BwUkQMtq1YmJ7JZvRdTZTQQY39mGnbfYbpEXRXsB7Mg"

[provider]
cluster = "localnet"
wallet = "wallets/localnet.json"

[features]
resolution = true
skip-lint = true
