[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[programs.localnet]
counter_authority = "2jM5zF1tN3UiYh6R6PCYJw3fd6kjYH1rcY4h4g3YFmV7"

[provider]
cluster = "localnet"
wallet = "wallets/localnet.json"

[features]
resolution = true
skip-lint = true
